# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-b7d04c14-9994-4203-b4e7-f7c834af8b7e";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-b7d04c14-9994-4203-b4e7-f7c834af8b7e".device = "/dev/disk/by-uuid/b7d04c14-9994-4203-b4e7-f7c834af8b7e";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/D317-DAFB";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/mnt/HDlinux" =
    { device = "/dev/disk/by-uuid/289299c0-f92e-49c7-9ae3-2fdd8f73ed03";
      fsType = "ext4";
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
